[package]
org = "Lee"
name = "DSA"
version = "2201.10.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mongodb-native"
version = "1.44.4"